/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: 'class',
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        brand: {
          primary: '#8b5cf6',
          secondary: '#6366f1',
        },
        dark: {
          surface: '#0e0e13',
          card: '#1b1b20',
          border: '#2e2d33',
          muted: '#94a3b8',
        },
        "secondary-fixed-dim": "#4edea3",
        "on-secondary-fixed-variant": "#005236",
        "secondary-fixed": "#6ffbbe",
        "on-tertiary": "#472a00",
        "on-surface": "#e4e1e9",
        "primary-fixed": "#e9ddff",
        "tertiary-fixed": "#ffddb8",
        "tertiary": "#ffb95f",
        "surface-container": "#1f1f24",
        "secondary": "#4edea3",
        "surface-variant": "#35343a",
        "error": "#ffb4ab",
        "primary-container": "#a078ff",
        "on-secondary-container": "#00311f",
        "surface-container-low": "#1b1b20",
        "inverse-surface": "#e4e1e9",
        "on-primary-fixed": "#23005c",
        "on-primary": "#3c0091",
        "on-primary-fixed-variant": "#5516be",
        "on-tertiary-fixed-variant": "#653e00",
        "surface-dim": "#131318",
        "on-primary-container": "#340080",
        "background": "#131318",
        "surface-tint": "#d0bcff",
        "on-error": "#690005",
        "tertiary-container": "#ca8100",
        "secondary-container": "#00a572",
        "on-secondary": "#003824",
        "surface": "#131318",
        "on-surface-variant": "#cbc3d7",
        "on-tertiary-fixed": "#2a1700",
        "surface-container-high": "#2a292f",
        "on-background": "#e4e1e9",
        "outline-variant": "#494454",
        "error-container": "#93000a",
        "on-tertiary-container": "#3e2400",
        "on-error-container": "#ffdad6",
        "inverse-primary": "#6d3bd7",
        "inverse-on-surface": "#303035",
        "primary": "#d0bcff",
        "surface-container-lowest": "#0e0e13",
        "tertiary-fixed-dim": "#ffb95f",
        "surface-bright": "#39383e",
        "on-secondary-fixed": "#002113",
        "outline": "#958ea0",
        "surface-container-highest": "#35343a",
        "primary-fixed-dim": "#d0bcff"
      },
      fontSize: {
        "body-md": ["14px", { "lineHeight": "20px", "fontWeight": "400" }],
        "headline-sm": ["18px", { "lineHeight": "28px", "fontWeight": "600" }],
        "label-sm": ["11px", { "lineHeight": "14px", "fontWeight": "600" }],
        "label-md": ["13px", { "lineHeight": "18px", "fontWeight": "500" }],
        "body-sm": ["12px", { "lineHeight": "16px", "fontWeight": "400" }],
        "body-lg": ["16px", { "lineHeight": "24px", "fontWeight": "400" }],
        "headline-md-mobile": ["20px", { "lineHeight": "28px", "fontWeight": "600" }],
        "headline-md": ["24px", { "lineHeight": "32px", "letterSpacing": "-0.01em", "fontWeight": "600" }],
        "display-lg": ["32px", { "lineHeight": "40px", "letterSpacing": "-0.02em", "fontWeight": "700" }]
      },
      spacing: {
        "element-gap": "0.75rem",
        gutter: "1rem",
        "stack-gap": "1.5rem",
        "card-internal-padding": "1.25rem",
        "container-padding": "1rem",
        "card-padding": "20px",
        "gutter-md": "16px",
        "container-margin": "24px",
        "section-gap": "32px",
      },
      fontFamily: {
        sans: ['"Plus Jakarta Sans"', 'sans-serif'],
        'headline-lg': ['"Plus Jakarta Sans"', 'sans-serif'],
        'code-sm': ['"Inter"', 'monospace'],
        "body-md": ["Inter"],
        "headline-sm": ["Inter"],
        "label-sm": ["Inter"],
        "label-md": ["Inter"],
        "body-sm": ["Inter"],
        "body-lg": ["Inter"],
        "headline-md-mobile": ["Inter"],
        "headline-md": ["Inter"],
        "display-lg": ["Inter"]
      },
      boxShadow: {
        'neon-green': '0 0 10px rgba(74, 222, 128, 0.5), 0 0 20px rgba(74, 222, 128, 0.2)',
        'neon-purple': '0 0 10px rgba(168, 85, 247, 0.5), 0 0 20px rgba(168, 85, 247, 0.2)',
        'neon-cyan': '0 0 10px rgba(34, 211, 238, 0.5), 0 0 20px rgba(34, 211, 238, 0.2)',
      },
      keyframes: {
        'pulse-glow': {
          '0%, 100%': { opacity: 1 },
          '50%': { opacity: 0.6 },
        },
        'ripple': {
          'from': { width: '0', height: '0', opacity: 0.5 },
          'to': { width: '400px', height: '400px', opacity: 0, transform: 'translate(-50%, -50%)' }
        },
        fadeIn: {
          from: { opacity: 0, transform: 'translateY(10px)' },
          to: { opacity: 1, transform: 'translateY(0)' },
        }
      },
      animation: {
        'pulse-glow': 'pulse-glow 2s infinite ease-in-out',
        'ripple': 'ripple 0.6s linear',
        'fade-in': 'fadeIn 0.5s ease-out forwards',
      }
    },
  },
  plugins: [
    require('@tailwindcss/container-queries'),
    require('@tailwindcss/forms'),
  ],
};
