/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        surface: "var(--color-surface)",
        "primary-fixed-dim": "var(--color-primary-fixed-dim)",
        error: "var(--color-error)",
        "primary-container": "var(--color-primary-container)",
        "inverse-surface": "var(--color-inverse-surface)",
        "surface-container-low": "var(--color-surface-container-low)",
        "on-surface-variant": "var(--color-on-surface-variant)",
        "tertiary-fixed-dim": "var(--color-tertiary-fixed-dim)",
        "secondary-fixed-dim": "var(--color-secondary-fixed-dim)",
        primary: "var(--color-primary)",
        secondary: "var(--color-secondary)",
        tertiary: "var(--color-tertiary)",
        "on-surface": "var(--color-on-surface)",
        "on-primary-container": "#ffffff",
        "outline-variant": "var(--color-outline-variant)",
        "surface-container-lowest": "var(--color-surface-container-lowest)",
        "surface-container": "var(--color-surface-container)",
      },
      spacing: {
        sm: "var(--spacing-sm)",
        md: "var(--spacing-md)",
        lg: "var(--spacing-lg)",
        xs: "var(--spacing-xs)",
        xl: "var(--spacing-xl)",
        "margin-desktop": "var(--spacing-margin-desktop)",
        "margin-mobile": "var(--spacing-margin-mobile)",
      },
      fontFamily: {
        "headline-lg-mobile": "var(--font-headline-lg-mobile)",
        "display-lg": "var(--font-display-lg)",
        "data-mono": "var(--font-data-mono)",
        "headline-lg": "var(--font-headline-lg)",
        "body-md": "var(--font-body-md)",
        "label-sm": "var(--font-label-sm)",
      },
    },
  },
  plugins: [],
};
